export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_DOB_CHANGED = 'LOGIN_DOB_CHANGED';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_FAILED_UNKNOWN_REASON = 'LOGIN_FAILED_UNKNOWN_REASON';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USERNAME_CREATE = 'REGISTER_USERNAME_CREATE';
export const REGISTER_DOB_CREATE = 'REGISTER_DOB_CREATE';
export const REGISTER_FIRSTNAME_CREATE = 'REGISTER_FIRSTNAME_CREATE';
export const REGISTER_LASTNAME_CREATE = 'REGISTER_LASTNAME_CREATE';
export const REGISTER_PHONENUMBER_CREATE = 'REGISTER_PHONENUMBER_CREATE';
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_FAILED_UNKNOWN_REASON = 'REGISTER_FAILED_UNKNOWN_REASON';
export const LIST_ITEM_CHANGE_REPORT = 'LIST_ITEM_CHANGE_REPORT';
export const LIST_ITEM_CHANGE_SUB_REPORT = 'LIST_ITEM_CHANGE_SUB_REPORT';
//Navigation actions
export const NAVIGATE_LOGIN = 'NAVIGATE_LOGIN';
export const NAVIGATE_HOME = 'NAVIGATE_HOME';
export const NAVIGATE_REGISTER = 'NAVIGATE_REGISTER';
export const NAVIGATE_LIST_ITEM = 'NAVIGATE_LIST_ITEM';
export const NAVIGATE_SIXSHEET_ADD_NEW = 'NAVIGATE_SIXSHEET_ADD_NEW';
